### ISSUE TITLE
The Faulty Gripper challenge

### ISSUE THREAD

**Issue by liuhaoran1** [usnistgov/ARIAC#181]
The Faulty Gripper challenge: When placing a product on an AGV, The product will fall out of The AGV.

```
drops:
  drop_regions:
    shipping_box_0_impeding:
      frame: agv1::kit_tray_1
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.2, 0.2, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: assembly_pump_red
      robot_type: kitting # or gantry
```
