### ISSUE TITLE
faulty_part

### ISSUE THREAD

**Issue by LKmubihei** [usnistgov/ARIAC#232]
Regarding faulty_part, it is set in the faulty_part challenge
But in the sample.yaml file, there are faulty parts too
![image](https://user-images.githubusercontent.com/114295414/234810857-65476fca-5e05-4427-8152-555ec27dda02.png)

 Does this mean that faulty_part could also appear on the bin?

**Comment by anthonydowns** [comment]
A faulty part can be any part in the environment, but you will only be notified that it is faulty when it goes through the quality control sensor on the AGV (I believe)

**Comment by zeidk** [comment]
Hello, 
The screen capture you posted seems to be from an older yaml file that we forgot to update. We are not using this way to set faulty parts in the environment.

The only way to set  faulty parts is with the ```challenges``` field. Here is an example:

```yaml
challenges:
  - faulty_part:
      order_id: 'MMB30H00'
      quadrant1: false
      quadrant2: true
      quadrant3: true
      quadrant4: true
```
