### ISSUE TITLE
Add ability to pass in additional build arguments to colcon build step.

### ISSUE THREAD

**Issue by AravindaDP** [usnistgov/ARIAC#343]
Sometimes teams may need to pass in additional CMake arguments in colcon build step.

e.g. `colcon build --cmake-args -DDOWNLOAD_YOLO_CONFIG=OFF -DENABLE_CUDNN=OFF -DCMAKE_DISABLE_FIND_PACKAGE_OpenMP=TRUE`

This is not supported by currently hard coded colcon build step used by https://github.com/usnistgov/ARIAC_evaluation/blob/main/automated_evaluation/container_scripts/build_competitor_code.py#L81

Hypothetical workaround/hack (Not tested) is to pre build with necessary arguments using the competitor pre build script and hope CMake cache will use same settings during the above colcon build step.

Suggestion
Can it be make possible to include these additional build arguments and append to above colcon build step through team evaluation configuration file?

e.g.

```
# team configuration for automated evaluation

team_name: "test_competitor"

github:
  repository: "github.com/usnistgov/nist_competitor.git"
  tag: "2024.2.2"
  personal_access_token: ""

build:
  pre_build_scripts: ["test_competitor_pre_build.sh"]
  additional_build_args: ["-DENABLE_CUDNN=OFF -DCMAKE_DISABLE_FIND_PACKAGE_OpenMP=TRUE"]

competition:
  package_name: "nist_competitor"
  launch_file: "competition.launch.py"
```
