### ISSUE TITLE
Parts auto-magically pop-off from AGV

### ISSUE THREAD

**Issue by avidacs** [usnistgov/ARIAC#41]
When running qual_a_2, some parts are suddenly dropped from the agv tray while the robot is picking up part somewhere else. 

Part dropped from agv2 tray: gasket_part_red, The config file includes: 

---
drop_regions:
    shipping_box_0_impeding:
      frame: agv1::kit_tray_1
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.3, 0.3, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gasket_part_red

---

But this drop happens on AGV2 and not from gripper but after the part already sitting on tray for a while. Is that behavior supposed to be normal?

I try to add a small video of the event
[auto-amgical-drop.zip](https://github.com/usnistgov/ARIAC/files/4464165/auto-amgical-drop.zip)

**Comment by zeidk** [comment]
Thank you, I will try to reproduce this issue. When submitting AGV2 do you still get points for parts that were popped off?

**Comment by avidacs** [comment]
Nope, no points for the dropped-off products.

**Comment by stevegray954** [comment]
Ha, that's a fun one.  Interesting that the parts move exactly when you pick up a new blue gear.  Looks like both red gaskets and blue gears are supposed to drop in the full version of the drop section: 

```
  drop_regions:
    shipping_box_0_impeding:
      frame: agv1::kit_tray_1
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.3, 0.3, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gasket_part_red
    shipping_box_1_impeding:
      frame: agv2::kit_tray_2
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.3, 0.3, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gear_part_blue
```

**Comment by stevegray954** [comment]
Edit: This actually makes a ton of sense.  

Quick fix:
Need to get rid of this part of the config file.  It's telling the red gaskets that they have a drop scheduled (see https://github.com/usnistgov/ARIAC/blob/ff420d41917defa9fdf84ae1f24c8950fa0959d2/nist_gear/src/VacuumGripperPlugin.cc#L602))

```
    shipping_box_0_impeding:
      frame: agv1::kit_tray_1
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.3, 0.3, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gasket_part_red
```

However, this doesn't fix the underlying issue.

The simulation has changed -- never before could the arm pick up a part and then not have it be dropped before picking up another part.  The red gasket goes to AGV2, so it never encounters AGV1 and gets dropped.  `dropPending` remains true.

Right here at https://github.com/usnistgov/ARIAC/blob/ff420d41917defa9fdf84ae1f24c8950fa0959d2/nist_gear/src/VacuumGripperPlugin.cc#L460, it just checks if any part is attached to the gripper and a drop is pending.  However, this line https://github.com/usnistgov/ARIAC/blob/ff420d41917defa9fdf84ae1f24c8950fa0959d2/nist_gear/src/VacuumGripperPlugin.cc#L464 should catch that the attached object is the wrong type.
