### ISSUE TITLE
kitting arm initial joints

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#90]
The kitting arm initial joints change from one run to the next.  Some of them are clearly wrong, as when it is bent over the rail.
The joint wrist1 joint seems to be off most frequently, varying from -2.7 to + 3.6.
Are there defined joints for the initial position of the arm?  If so, will contest runs that have it starting with incorrect joints be rerun?

**Comment by zeidk** [comment]
Do all the controllers start when you start the simulation? I have not noticed this at all and I'm curious as to how you have this behavior. Do you mind uploading a log file?

**Comment by denbar-robotics** [comment]
Sure, which log file do you want?  All the controllers load OK.  There are no errors in performance.log  This happens about 20% of the time.  The arm works OK, it would just be nice to know where it is going to start.

I'm attaching an image as an example.  Here are the joint states:

```
header: 
  seq: 4995
  stamp: 
    secs: 99
    nsecs: 922000000
  frame_id: ''
name: [elbow_joint, linear_arm_actuator_joint, shoulder_lift_joint, shoulder_pan_joint,
  vacuum_gripper_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]
position: [-0.6114049668683714, 0.014174808482274743, 0.3009926442078008, -0.043833719881464894, -7.716944956825955e-06, -0.18999951386964886, 0.5113663472643486, 1.0543961338560592]
velocity: [-0.3611036343328132, -0.00275868007088335, 0.11553725374175966, 0.00322258210696799, -0.001824431520466836, 0.10673331343770576, -0.0038725146651870015, 0.05741614411719662]
effort: [-76.63983908208905, -37.06571039422064, 330.0, 38.91498422065733, 0.0, 0.29486501465384285, -0.00857803806322281, 0.04827968001563422]
---
```
![starting_arm_collapsed_over_belt_cropped](https://user-images.githubusercontent.com/78889039/113959338-ad472c00-97f0-11eb-8b79-9ef8ba1751c2.png)
